import mongoose from "mongoose";
import mongooseAggregatePaginate from "mongoose-aggregate-paginate-v2";

const bookingSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    carId: { type: mongoose.Schema.Types.ObjectId, ref: "Car", required: true },
    pickupLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location", required: true },
    dropoffLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location", required: true },
    pickupDate: { type: String, required: true },
    pickupTime: { type: String },
    returnDate: { type: String, required: true },
    returnTime: { type: String },
    status: {
      type: String,
      enum: ["pending", "confirmed", "checked_in", "checked_out", "completed", "cancelled"],
      default: "confirmed",
    },
    totalAmount: { type: Number, required: true },
    bookedDailyRate: { type: Number },
    bookedDailyMileageLimit: { type: Number },
    bookedChargePerExtraKm: { type: Number },
    serviceSnapshots: [
      {
        serviceId: { type: mongoose.Schema.Types.ObjectId, ref: "AdditionalService" },
        name: { type: String, required: true },
        dailyRate: { type: Number, required: true },
        chargeType: { type: String, enum: ["per_day", "per_trip"], default: "per_day" },
        category: { type: String },
        allowQuantity: { type: Boolean, default: false },
        quantity: { type: Number, min: 1, default: 1 },
      },
    ],
    checkInMileage: { type: Number },
    checkOutMileage: { type: Number },
    totalDrivenKm: { type: Number },
    allowedMileageKm: { type: Number },
    extraMileageKm: { type: Number },
    extraMileageCharge: { type: Number, default: 0 },
    additionalServiceIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "AdditionalService" }],
    serviceQuantities: [
      {
        serviceId: { type: mongoose.Schema.Types.ObjectId, ref: "AdditionalService" },
        quantity: { type: Number, min: 1, default: 1 },
      },
    ],
    extraDriverCount: { type: Number },
    extraDriverNames: [{ type: String }],
    licenseUrl: { type: String },
    extraDriverLicenseUrl: { type: String },
    checkInVisibleToUser: { type: Boolean, default: false },
    checkOutVisibleToUser: { type: Boolean, default: false },
    notes: { type: String },
    paymentStatus: {
      type: String,
      enum: ["pending", "paid", "refunded"],
      default: "pending",
    },
    securityDepositAmount: { type: Number },
    securityDepositStatus: {
      type: String,
      enum: ["held", "partially_used", "refunded"],
    },
    securityDepositHeldAt: { type: Date },
    securityDepositRefundedAt: { type: Date },
    securityDepositRefundedAmount: { type: Number },
    invoiceSequence: { type: Number, default: 0 },
    checkInBillSnapshot: {
      capturedAt: { type: Date },
      entries: [
        {
          entryId: { type: String },
          title: { type: String },
          description: { type: String },
          amount: { type: Number },
          entryType: { type: String },
          status: { type: String },
          source: { type: String },
          phase: { type: String },
          systemKey: { type: String },
          createdByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
          createdByName: { type: String },
          createdByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
          taxAmount: { type: Number },
          totalAmount: { type: Number },
        },
      ],
    },
    checkOutBillSnapshot: {
      capturedAt: { type: Date },
      entries: [
        {
          entryId: { type: String },
          title: { type: String },
          description: { type: String },
          amount: { type: Number },
          entryType: { type: String },
          status: { type: String },
          source: { type: String },
          phase: { type: String },
          systemKey: { type: String },
          createdByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
          createdByName: { type: String },
          createdByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
          taxAmount: { type: Number },
          totalAmount: { type: Number },
        },
      ],
    },
    cancellationReason: { type: String },
    cancelledBy: { type: String, enum: ["user", "admin"] },
    cancellationPolicy: { type: String, enum: ["one_day_fee", "non_refundable"] },
    cancellationRefundAmount: { type: Number },
    createdByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    createdByName: { type: String },
    createdByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
    updatedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    updatedByName: { type: String },
    updatedByRole: { type: String, enum: ["admin", "sub_admin"] },
    checkInPerformedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    checkInPerformedByName: { type: String },
    checkInPerformedByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
    checkOutPerformedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    checkOutPerformedByName: { type: String },
    checkOutPerformedByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
    billEntries: [
      {
        title: { type: String, required: true },
        description: { type: String },
        amount: { type: Number, required: true, min: 0 },
        entryType: { type: String, enum: ["charge", "payment"], required: true },
        status: {
          type: String,
          enum: ["unpaid", "paid", "refund"],
          default: "unpaid",
        },
        source: { type: String, enum: ["system", "manual"], default: "manual" },
        phase: { type: String, enum: ["check_in", "check_out", "post"] },
        systemKey: { type: String },
        createdByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        createdByName: { type: String },
        createdByRole: { type: String, enum: ["admin", "sub_admin", "customer"] },
        taxAmount: { type: Number },
        totalAmount: { type: Number },
        invoiceNumber: { type: String },
        invoicePdfUrl: { type: String },
        paidVia: { type: String, enum: ["e_transfer", "deposit"] },
        attachmentUrl: { type: String },
        attachmentName: { type: String },
      },
    ],
  },
  { timestamps: true },
);

bookingSchema.plugin(mongooseAggregatePaginate);
export const Booking = mongoose.model("Booking", bookingSchema);
